/* Generated by Yosys 0.9+4303 (git sha1 c88eaea6, clang 11.0.1-2 -fPIC -Os) */

module spi_slave(ss, sclk, sdi, reset, data);
  wire _0_;
  wire [7:0] _1_;
  output [7:0] data;
  input reset;
  input sclk;
  input sdi;
  reg [7:0] shift_reg;
  input ss;
  assign _1_ = _0_ ? { shift_reg[6:0], sdi } : shift_reg;
  always @(posedge sclk, posedge reset)
    if (reset) shift_reg <= 8'h00;
    else shift_reg <= _1_;
  assign _0_ = ~ ss;
  assign data = shift_reg;
endmodule
