/* Generated by Yosys 0.9+4303 (git sha1 c88eaea6, clang 11.0.1-2 -fPIC -Os) */

module spi_slave(ss, sclk, sdi, reset, data);
  wire _0_;
  wire _1_;
  wire [7:0] _2_;
  output [7:0] data;
  input reset;
  input sclk;
  input sdi;
  reg [7:0] shift_reg;
  input ss;
  assign _2_ = _1_ ? { shift_reg[6:0], sdi } : shift_reg;
  always @(posedge sclk, posedge _0_)
    if (_0_) shift_reg <= 8'h00;
    else shift_reg <= _2_;
  assign _0_ = ~ reset;
  assign _1_ = ~ ss;
  assign data = shift_reg;
endmodule
